name: Compatibility Tests

# TODO: Reinstate before merge to main
#on:
#  schedule:
#    - cron: '0 8 7 * 2'
#  push:
#    branches:
#      - main

# TEMPORARY
# TODO: Remove before merge to main
on:
  push:
    branches:
      - atolopko/2410-update-compatibility-test-matrix

env:
  JEST_ENV: prod
  CXG_AUTH_TYPE: none

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build docker image
        run: docker build .

  cellxgene-main-with-python-and-os-versions:
    name: python versions тип os versions
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        # note: The `macos-latest` is latest Catalina version, and not Big Sur. So we explicitly ask for Big Sur (`macos-11`)
        os: [ubuntu-latest, macos-latest, macos-11]
        # python-version: [3.8]
        # TODO: Reinstate before merge to main
        python-version: [3.6, 3.7, 3.8, 3.9]
        cellxgene_build: [main, release]
        anndata_version: ['==0.7.6', '']
        exclude:
          # 3.6 no longer avail on Big Sur (`macos-11`)
          - os: macos-11
            python-version: 3.6
          # macos+py3.9 fails to install `tables` py pkg (a `scanpy`
          # dependency), so we add py3.9 only for ubuntu
          - os: macos-11
            python-version: 3.9
          - os: macos-latest
            python-version: 3.9
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies (Ubuntu Linux)
      if: startsWith(${{ matrix.os }}, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install -y libhdf5-serial-dev
    - name: Install dependencies (MacOS)
      if: startsWith(${{ matrix.os }}, 'macos')
      run: brew install hdf5
    - name: Install cellxgene from main (latest)
      if: ${{ matrix.cellxgene_build }} == 'latest'
      run: |
        # only install the dev requirements on top of what is in the
        # cellxgene pip package
        sed -i'' -e 's/-r requirements.txt//' backend/server/requirements-dev.txt
        pip install -r backend/server/requirements-dev.txt
        make pydist install-dist
    - name: Install cellxgene from release (pypi.org)
      if: ${{ matrix.cellxgene_build }} == 'release'
      run: pip install --upgrade cellxgene
    - name: Install anndata version per matrix variable
      run: pip install anndata${{ anndata_version }}
    # - name: Tests
    #   run: make test

